### ISSUE TITLE
Show track name with audio fingerprinting

### ISSUE THREAD

**Issue by raphaelh** [haecker-felix/gradio#134]
Thanks to https://acoustid.org/ it would be possible to lookup track names for radio stations that don't include them with the audio stream. Wouldn't it be nice? :smile:

**Comment by haecker-felix** [comment]
Nice service. Maybe for the future 👍

**Comment by haecker-felix** [comment]
Unfortunately this is not possible.

_Can the service identify short audio snippets?
No, it can't. The service has been designed for identifying **full audio files**._

So it isn't possible to get the metadata while the song is playing.

**Comment by raphaelh** [comment]
I should have provided this link instead: https://oxygene.sk/2016/12/chromaprint-1-4-released/

> The biggest feature is that all components of audio fingerprinting process now work in a streaming fashion and can provide partial results at any time. That means that it's now possible to feed a continuous audio stream to the process and get back partial fingerprints. This is useful if you want to fingerprint e.g. an internet radio stream and do not want to explicitly split the stream into small chunks. There are also side effects of these changes and the whole process is now faster and uses less memory.

**Comment by haecker-felix** [comment]
Chromaprint supports generating fingerprints from internet streams, but I don't know what i can do with this information, because it isn't the fingerprint from the whole song, which i need for acoustid.

(See https://acoustid.org/webservice , Lookup by fingerprint)

**fpcalc -ts -chunk 10 -overlap -json http://icecast2.play.cz/radio1.mp3**
`{"timestamp": 1487067423.80, "duration": 12.60, "fingerprint": "AQAAUAkjLlOIo1mXKuh1aId1XZh08I8xJ6mNd8eTQ8vR48eTJDrO0eixXRGYK9Dz4HyC52iaSaioJVgdiRR6wr8SWM8brItwPod_iB-uPEXzI_qC38G-4z1TWPswWimSH_nxpsaHn3ieDT-F8EiW_NgF8jnmKsI19Ap8HZ6Vhkj4IPxxPfjRPOiPBxeVClOlC9SDizO-w7F2_Dj6ByF1UCSRvNgfOMooGqWiBdfRD2oEAgIDQIADyBAKIFDAAEgMI0QQAoACghBGgEIGCAIIYpARhphAxgFlkCHMGAGwBopAgZSTxCBhFCAYAqSAMYhZ"}`

http://api.acoustid.org/v2/lookup?client=bN6wzb44nAg&duration=641&fingerprint=AQAAUAkjLlOIo1mXKuh1aId1XZh08I8xJ6mNd8eTQ8vR48eTJDrO0eixXRGYK9Dz4HyC52iaSaioJVgdiRR6wr8SWM8brItwPod_iB-uPEXzI_qC38G-4z1TWPswWimSH_nxpsaHn3ieDT-F8EiW_NgF8jnmKsI19Ap8HZ6Vhkj4IPxxPfjRPOiPBxeVClOlC9SDizO-w7F2_Dj6ByF1UCSRvNgfOMooGqWiBdfRD2oEAgIDQIADyBAKIFDAAEgMI0QQAoACghBGgEIGCAIIYpARhphAxgFlkCHMGAGwBopAgZSTxCBhFCAYAqSAMYhZ

Output:
`{"status": "ok", "results": []}`

I've tried this many times, always no result. Maybe i'm doing something wrong, i never worked with audio fingerprinting / acoustid before. But I'm realy interested to implent something like this in gradio.
