### ISSUE TITLE
...suggestion about radio station details window

### ISSUE THREAD

**Issue by dasnoopy** [haecker-felix/gradio#179]
I guess is all still w.i.p. and you already plan to revised the details window,  but instead to use a separate windows, maybe you  could try to change it and use e.g. a sidebar in the main window where display info about radio station. then using a the details button you could switch on/off the details sidebar... 

Regards 
Andrea

**Comment by haecker-felix** [comment]
I like idea. But when does the sidebar appear? If i click on item, the playback starts, or the collection opens.

**Comment by dasnoopy** [comment]
just some very personal ideas  (feel free to rejct them :-)))) ) 

...  if you'll implement sidebar for detail info , what about to:

- **change** the current behaviour using **double click** to **start playback**...

- then, you could add  an option in preferences to  enable/disable sidebar for detail (if  enabled,  sidebar should be visibile only in **library** or **collections** mode) :

  - if "show detail sidebar" preferences is set always ON single click on any station will update the info for selected station on sidebar (without start playback). A double click on station obviously will start playback and update  info on sidebar.
 
  - If  "show detail sidebar" preference  is set always OFF  ,  single click on station will do nothing while as "usual" a double click on station  will start playback and update  info on sidebar.

- in **search** mode ,   a sidebar  is already used for  parameters : in this case, again,  show details could be  a _gtkpopover_ widget that showing basic info and  it appears when you simple click on any station (while a  double click  on station will start playback )

- in **preferences** mode  , detail sidebar should never be diplayed (also if option is ON)

In all modes , you could always get some  basic station info using  popover  when you click on station icon in the  bottom player bar (more or less like with previous versions of gradio). 

Regards

**Comment by haecker-felix** [comment]
I think there shouldn't be a toggle for the sidebar in the settings. 

The first click on a station, starts the playback. The second click opens the details sidebar. And this behaviour should be consistent in gradio. Why it shouldn't be possible to see the station details in the search page? I think there are the details most importantly. And if the user wants to see the details without starting the playback, you can simply make a right click on the station and select "details". 

The problem is (as you have already said), in the search page, there is already the filter sidebar. It would be not a problem, to place the details sidebar to the right side, but then there isn't much space available for the stations anymore.

That means if we go the way with the sidebar, the filterbox in the search page has to be moved to elsewhere. But where? 

Ideas:
- Move it into a popover?
- Make it only visible when you need it?
- Auto hide the sidebar?
- ...?

There are many ways, but no way is perfect :/.

**Comment by dasnoopy** [comment]
.. the GtkSearchBar with a joined button for  filterbox popover  could be what we need... :)

* https://developer.gnome.org/gtk3/stable/GtkSearchBar.html

**Comment by haecker-felix** [comment]
https://camo.githubusercontent.com/eb826c7a3396b6a2af0f45c70b49f0742f77ada7/687474703a2f2f692e696d6775722e636f6d2f686a59303746382e706e67

You mean something like this?

The problem is, the user doesn't see which search filter is applied.

**Comment by dasnoopy** [comment]
yes.. exaclty something like that could be nice...

so if I understand  , you are worried about the fact that when you choose a lots of filters,  all tags could not be  displayed  in the text entry?

If so, I don't have the answer : i'm not a programmer but maybe gtk developers already managed this "issue" and if you have a lot of tags maybe they are truncated in some way.  You should try ... :-)))

**Comment by haecker-felix** [comment]
Unfortunately not, the special search entry is provided by the gd library and haven't got updated  the last time.

I'm planning to move the "Sort by" options into the headerbar, to make it available for all pages (sorting in the library...). And with this step, it is maybe possible to fit all the selected filter options in the search entry. I hope you know what i mean :-)

You can test the libgd searchentry in nautilus (search).

**Comment by haecker-felix** [comment]
I'm finished the redesign of the search page. 

Now I'm using the libgd tagged entry. I think now it is way better than before. Now there should be enough space for the details sidebar :).

**Comment by haecker-felix** [comment]
![sidebardemo](https://user-images.githubusercontent.com/6001248/27988679-0c620b16-6428-11e7-8415-f73a0ace8f7d.png)


:)

**Comment by dasnoopy** [comment]
.. thank so much  for the implementation of new search toolbar and the details sidebar :  really well done :)))
