### ISSUE TITLE
No menu settings displayed

### ISSUE THREAD

**Issue by dino99** [haecker-felix/gradio#235]
Running ubuntu 17.10 (Artful) with a gnome-shell DE & wayland session.
Installed the nightly flatpak version to try getting that hidden 'Settings' menu, as the previous 6 versions also miss it. But here too the icons are not displayed.

Is there some missing dependency(ies) or 'theme' required or special font ?
note that i'm using (default installation) python3-xdg

**Comment by haecker-felix** [comment]
Well, the settings menu should't be "hidden". You can find it in the app menu (if you are using the GNOME Shell).

![bildschirmfoto vom 2017-11-06 17-04-01](https://user-images.githubusercontent.com/6001248/32450541-bed06b1c-c314-11e7-9929-90d2d2ad4032.png)


Can you provide a screenshot? Which icons are missing? This *might* be a flatpak issue because Ubuntu is using a outdated flatpak version. You should prefer the Flatpak PPA:
http://flatpak.org/getting (Ubuntu section)

**Comment by haecker-felix** [comment]
Huh? No answer? I can't fix this issue, if i don't get more information.

**Comment by dino99** [comment]
Does not know about the changes made on the system, but now the 'settings' menu is displayed.
So closing that issue.
Thanks for your work.
