### ISSUE TITLE
[Feature Request] Improve tray icon

### ISSUE THREAD

**Issue by Generator** [haecker-felix/gradio#262]
## Expected Behavior

Ability to control Gradio from tray icon

## Current Behavior

Tray icon is almost useless, the current behavior is to restore main window, some improvements could help users to control Gradio:

- Menu with Pause/Stop controls
- Menu next/previous radio from users library
- Menu close Gradio
- Middle mouse click Pause/Stop
- Add current radio to users library
- Left click minimize to tray
- Mouse over tray icon show current radio info/status
- Minimize to tray
- Start on tray/minimized

## Detailed Description

I'm a XFCE user and tray icons are important for most os non Unity/Gnome users, ability to control the application from tray icon is more simpler instead of restoring main window every time.

**Comment by haecker-felix** [comment]
I don't add additional features to the tray icon, because it is a deprecated technology. More information here: 

https://github.com/haecker-felix/gradio/issues/176

Gradio uses MPRIS for a desktop media player integration. XFCE + MPRIS more information here: 
https://www.youtube.com/watch?time_continue=36&v=ayKd0mqmmjM (for example. There are may be other ways)
