### ISSUE TITLE
Automatic resume from suspend

### ISSUE THREAD

**Issue by orschiro** [haecker-felix/gradio#265]
Dear all, 

Can we resume playback automatically on resume from suspend?

Steps I tried with version 7 on Linux Mint 18.3 Cinnamon:

1. Start the radio
2. Close my lid to suspend my laptop
3. Open lid again to resume
4. I hear the radio for ~2 more seconds before the playback stops
5. I need to manually restart the radio

**Comment by orschiro** [comment]
Hmm, strangely sometimes it is actually resuming the playback after suspend. Maybe my WiFi (Thinkpad X230) doesn't sometimes switch off during standby?

Can someone tell me how that looks like on his or her system?

**Comment by haecker-felix** [comment]
Thank you for your little suprise 😄. I'll look after it, currently I'm bit busy. Sorry!

I can reproduce you behaviour. I start the playback, go to hibernate mode, open lid again and hear 2 seconds playback.

This is a bit strange, because Gradio is still showing "Connected". 

Normally Gradio should automatically reconnect to the radio stream, if the connection is broken. You can test this, by disconnecting to your wifi, wait a bit, and reconnect.

**Comment by orschiro** [comment]
> Thank you for your little suprise

You're welcome. :smile: 

> Normally Gradio should automatically reconnect to the radio stream, if the connection is broken. You can test this, by disconnecting to your wifi, wait a bit, and reconnect.

Wow, cool. Yes, that works, nice! Hopefully we can implement exactly this also for the resume from suspend.

**Comment by haecker-felix** [comment]
I don't get it... Since my latest changes, i cannot reproduce this behaviour anymore... 

Could you try the latest git version?
If you are using flatpak, you can use this bundle:

https://drive.google.com/file/d/1maUCJ8OH7D7yDaMJAVqe2frSOtQvmNei/view?usp=sharing

**Comment by orschiro** [comment]
> Could you try the latest git version?

@haecker-felix you're great, it's working! :smile:
