### ISSUE TITLE
Crash when trying to select English or Spanish language from within languages

### ISSUE THREAD

**Issue by elpraga** [haecker-felix/gradio#50]
Ubuntu 14.04

this is the message I get:
```
(gradio:10263): GLib-ERROR **: creating thread 'image_thread': Error creating thread: Resource temporarily unavailable
Trace/breakpoint trap
```

**Comment by haecker-felix** [comment]
I cannot reproduce this bug. A workaround would be to disable image downloading in the settings. I know the current image management system is very bad. The next release of gradio will contain a better one. 

This bug is closed because gradio doesn't support ubuntu 14.04 officially. If you have more questions feel free to ask ;)
