### ISSUE TITLE
Some sparse suggestions (with mockup) ...

### ISSUE THREAD

**Issue by dasnoopy** [haecker-felix/gradio#99]
.. just an ugly mockup showing some very personal  ideas that I'd like to see adopted  in future
versions of gradio  :-)  

![gradiio_suggestions](https://cloud.githubusercontent.com/assets/296922/19836756/7b328f5a-9eaa-11e6-924f-897f238f55f0.png)

Thanks in advance
Andrea

**Comment by haecker-felix** [comment]
Short Feedback:

The grey bar on the right side should be a info bar without any button (How many likes, already in library, actually playing).

I think the logos looks better with a border. But that is my opinion. I'll make a option for the settings.

5: Okay nice idea, but how does the user know that the logo is a button?

6/7: Mhm. Idk. Let's see :thinking:

**Comment by bil-elmoussaoui** [comment]
Also to add some suggestions, please use Gtk.Spinner instead of showing the three dots icons.. As the user won't notice that something loading this way...
Also, can you move the search bar from the header bar and show it when the user hits CTRL + F or click on the search button ? The same way it's done on other gnome applications...

**Comment by haecker-felix** [comment]
Many of the suggestions are now in 5.x :)

Thanks!
